# Generated by Django 4.1.5 on 2023-01-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("OrderDate", models.DateField(blank=True, null=True)),
                ("Region", models.CharField(default="", max_length=50)),
                ("City", models.CharField(default="", max_length=50)),
                ("Category", models.CharField(default="", max_length=50)),
                ("Product", models.CharField(default="", max_length=50)),
                ("Quantity", models.IntegerField(default=" ")),
                ("UnitPrice", models.FloatField(default="", max_length=50, null=True)),
            ],
        ),
    ]
